### PR TITLE
Updated vimproc neobundle declaration according to docs.

### PR DESCRIPTION
**Pull request by JosephBuchma**
Automatically build vimproc native extensions.

### CODE REVIEW

**Comment by vitaly** [comment]
`vimproc` is already built by the `Makefile`. see `compile-vimproc` target.

From what I can see the root `Makefile` of `vimproc` already detects OS and compiles accordingly, so I wander why is all this complication needed.

anyway, I'm ok with following the `vamproc` docs, but we need to remove its compilation from `dotvim` `Makefile`

**Comment by JosephBuchma** [comment]
For some reason It doesn't worked for me. I had to compile vimproc by hand. 
After adding this vimproc have been compiled automatically during installation (I reinstalled everything from scratch for test).
Ubuntu 14.04

**Comment by vitaly** [comment]
a) did you run 'make install'?

b) as I wrote above, I'm ok with doing it this way, but please complete the PR by removing the compile-vimproc target from the root make file

**Comment by JosephBuchma** [comment]
I had done everything as described in dotvim installation guide (including `make install`). At the begining of 'neobundling' I had an error that vimproc was not compiled, so I had to go to `~/.vim/bundle/vimproc.vim` and run `make` there.

Ok, I'll clean up makefile.

**Pull request merged**
