### PR TITLE
Added multiple cursors plugin

### PR DESCRIPTION
**Pull request by JosephBuchma**
Hi. Why [this](https://github.com/terryma/vim-multiple-cursors) plugin still is not included?

### CODE REVIEW

**Comment by JosephBuchma** [comment]
Crap..
Accidentally made this pr from master branch. Would you like to include this plugin? If yes, I'll close this pr and make another one from separate branch.

**Comment by vitaly** [comment]
I looked at this plugin once, and didn't find it easy enough to user to be generally useful. might take a look at it again though ;). from a quick look it seems it has some mapping problems with the current `dotvim`. for example `ctrl-n` is already used. need to how to solve it.

**Comment by JosephBuchma** [comment]
I used multiple cursors heavily in Sublime Text for a long time before switching to Vim, very handy feature.
As I see `ctrl-n` is the only collision. The only binding that is accessible from normal mode is `multi_cursor_start_key`, which is `ctrl-n` by default, others are active just when you in multiple cursors mode. 
I think it can be reconfigured in this way:
```

let g:multi_cursor_use_default_mapping=0
" Fixed collision here, everything else is default
let g:multi_cursor_start_key='<Leader>nn'
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

```

**Comment by vitaly** [comment]
Remapping "<Leader>nn" will be a significant slow down for the "<Leader>n"
which is 'go to next match' for grep and the like. It will have to wait to
see if its followed by another 'n'. It is usually quite annoying ;)

It still feels more of a 'vimrc.after' then 'generally useful' kind of
thing ;)

--
Vitaly Kushner (@vkushner)
Founder, Astrails Ltd. http://astrails.com/
We create awesome web applications.

**Pull request closed without merging**
